fix(migrations): encode input to ensure valid postgres urls
graphql-hive/console pull request #6123
Opened 2024-12-13 16:50 UTC by Intellicode

### Background

When passwords (or other parameters) contain special characters (such as `%` in a password), it will result in invalid postgres url's

### Description

The change encodes all injected input parameters, I can remove some if you think its unnecessary.

### Checklist

- [x] Input validation
- [ ] Output encoding
- [ ] Authentication management
- [ ] Session management
- [ ] Access control
- [ ] Cryptographic practices
- [ ] Error handling and logging
- [ ] Data protection
- [ ] Communication security
- [ ] System configuration
- [ ] Database security
- [ ] File management
- [ ] Memory management
- [ ] Testing

2024-12-16 10:31 UTC, n1ru4l requested changes
Hey @Intellicode, thank you for this contribution. There are currently multiple `createConnectionString` copies within our code base e.g.

```
packages/services/storage/src/db/utils.ts
packages/migrations/src/connection-string.ts
```

Could you adjust all of them to use the same function definition with your improvements?

Also could you please add a changeset for `hive` using the command `pnpm changeset`, for describing this improvement?

2024-12-23 13:03 UTC, Intellicode commented
@n1ru4l Thanks for your feedback! I've modified the other places to include the logic, I've also made password optional, since some authentication mechanisms allow disabling of password based login (such as in Azure with Workload ID's on Kubernetes)

2024-12-27 09:50 UTC, n1ru4l commented on packages/migrations/src/environment.ts
> +  POSTGRES_PASSWORD: zod.string().optional(),
```suggestion
  POSTGRES_PASSWORD: emptyString(zod.string().optional()),
```

2024-12-27 09:50 UTC, n1ru4l commented on packages/services/storage/src/environment.ts
> +  POSTGRES_PASSWORD: zod.string().optional(),
```suggestion
  POSTGRES_PASSWORD: emptyString(zod.string().optional()),
```

2024-12-27 10:16 UTC, n1ru4l requested changes
@Intellicode Can you also update the configuration of other services that access postgres and the READMEs (mark password as optional env variable).

Please also add a changeset for `graphql-hive`

2025-01-16 09:31 UTC, n1ru4l requested changes
Updates to the following files are missing:
- https://github.com/graphql-hive/console/blob/main/packages/services/rate-limit/src/environment.ts
- https://github.com/graphql-hive/console/blob/main/packages/services/stripe-billing/src/environment.ts
- https://github.com/graphql-hive/console/blob/main/packages/services/tokens/src/environment.ts
- https://github.com/graphql-hive/console/blob/main/packages/services/usage-estimator/src/environment.ts
- https://github.com/graphql-hive/console/blob/main/packages/services/server/src/environment.ts

2025-01-23 13:29 UTC, merged